on:
  push:
    # delete this item if you don't want to trigger this workflow when modify this repo
    branches: master
  schedule:
    # * is a special character in YAML so you have to quote this string
    # UTC 17:00 -> CST (China) 1:00, see https://datetime360.com/cn/utc-cst-china-time/
    - cron: '0 20 * * *'
name: Sync github to gitee
jobs:
  run:
    name: Sync-GitHub-to-Gitee
    runs-on: ubuntu-latest
    steps:
    - name: Cache src repos
      uses: actions/cache@v2.1.3
      id: cache
      with:
        path: ${{ github.workspace }}/hub-mirror-cache
        key: ${{ runner.os }}-${{ steps.info.outputs.key }}-cache-${{ steps.info.outputs.time }}
        restore-keys: ${{ runner.os }}-${{ steps.info.outputs.key }}-cache-

    - name: Sync-GitHub-to-Gitee 
      uses: Yikun/hub-mirror-action@v1.1
      with:
        src: github/KangLin
        dst: gitee/kl222
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        force_update: true
        #account_type: user
        cache_path: ${{ github.workspace }}/hub-mirror-cache
        timeout: 600
        static_list: "RabbitCommon,RabbitIm,ChineseChessControl,LunarCalendar,Calendar,SerialPortAssistant,TransformCoordinate,windows_right_menu,RabbitRemoteControl,RabbitProxyServer,Documents,FaceRecognizer,QtAndroidUtils,ProfitCalculation,AndroidLockScreen,RabbitGIS,RabbitVNC,GoogleMapPluginForQt,WanNiLi.Gadget"
      
    - name: Print cache path
      run: |
          ls -la ${{ github.workspace }}/hub-mirror-cache

    - name: mirror
      uses: KangLin/mirror-action@master
      with:
        GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
        GIT_SSH_NO_VERIFY_HOST: "true"

          
