on:
  push:
    # delete this item if you don't want to trigger this workflow when modify this repo
    branches: master
  schedule:
    # * is a special character in YAML so you have to quote this string
    # UTC 17:00 -> CST (China) 1:00, see https://datetime360.com/cn/utc-cst-china-time/
    - cron: '0 1 * * *'
name: Sync github to gitee
jobs:
  run:
    name: Sync-GitHub-to-Gitee
    runs-on: ubuntu-latest
    steps:
    - name: Sync-GitHub-to-Gitee 
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/KangLin
        dst: gitee/kl222
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        force_update: true
        #account_type: user
        #cache_path:
        timeout: 600
        static_list: "Calendar, RabbitCommon, RabbitIm, ChineseChessControl, LunarCalendar, SerialPortAssistant, TransformCoordinate"
